# to apply all branches except master branch
# https://stackoverflow.com/questions/57699839/github-actions-how-to-target-all-branches-except-master

on:
  push:
    branches-ignore:
      - master
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Install packages
        run: npm install
      - name: Prettier
        run: npm run format
      - uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: Apply formatting changes
            branch: ${{ github.head_ref }}

